version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/InstallationChecking.Pn"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microting.InstallationCheckingBase
    versions:
    - 2.0.101
    - 2.0.102
    - 2.0.103
    - 2.0.105
    - 2.0.106
    - 2.0.107
    - 2.0.108
    - 2.0.92
    - 2.0.94
    - 2.0.96
    - 2.0.97
    - 2.0.98
    - 2.0.99
    - 2.1.0
    - 2.1.1
  - dependency-name: Microting.eFormApi.BasePn
    versions:
    - 2.0.100
    - 2.0.101
    - 2.0.102
    - 2.0.103
    - 2.0.104
    - 2.0.106
    - 2.0.107
    - 2.0.108
    - 2.0.110
    - 2.0.111
    - 2.0.112
    - 2.0.113
    - 2.0.116
    - 2.0.117
    - 2.0.118
    - 2.0.122
    - 2.0.126
    - 2.0.127
    - 2.0.128
    - 2.0.97
    - 2.0.98
    - 2.0.99
    - 2.1.0
    - 2.1.2
  - dependency-name: Microting.eFormBaseCustomerBase
    versions:
    - 2.0.101
    - 2.0.102
    - 2.0.103
    - 2.0.105
    - 2.0.106
    - 2.0.107
    - 2.0.108
    - 2.0.110
    - 2.0.111
    - 2.0.112
    - 2.0.114
    - 2.0.115
    - 2.0.116
    - 2.0.117
    - 2.0.96
    - 2.0.97
    - 2.0.98
    - 2.0.99
    - 2.1.0
    - 2.1.1
  - dependency-name: Microting.eForm
    versions:
    - 4.3.14
    - 4.3.17
    - 4.3.18
    - 4.4.1
    - 4.4.11
    - 4.4.13
    - 4.4.14
    - 4.4.17
    - 4.4.19
    - 4.4.2
    - 4.4.20
    - 4.4.22
    - 4.4.24
    - 4.4.26
    - 4.4.27
    - 4.4.3
    - 4.4.31
    - 4.4.35
    - 4.4.36
    - 4.4.37
    - 4.4.4
    - 4.4.6
    - 4.4.7
    - 4.4.9
    - 4.5.0
    - 4.5.2
  - dependency-name: EPPlus
    versions:
    - 5.5.2
    - 5.5.3
    - 5.5.4
    - 5.5.5
    - 5.6.0
    - 5.6.1
    - 5.6.2
  - dependency-name: Magick.NET-Q16-x64
    versions:
    - 7.23.2.1
    - 7.23.3
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: Magick.NET-Q8-x64
    versions:
    - 7.23.2
  - dependency-name: NUnit
    versions:
    - 3.13.0
